name: Build Windows Application_pata8_p2i

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install pillow
          pip install pdf2image
          # tkinterのインストールを除外します

      - name: Install Poppler for Windows
        run: |
          choco install poppler

      - name: Build the application
        run: |
          pyinstaller --onefile --windowed pata8_p2i.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Windows-app
          path: dist/pata8_p2i.exe  # 正しいファイルパスを指定
