name: Build and Package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pillow tkinter pdf2image pyinstaller
        
    - name: Install Poppler
      run: sudo apt-get update && sudo apt-get install -y poppler-utils

    - name: Generate EXE
      run: |
        pyinstaller --onefile --noconsole your_script.py
