name: Build macOS Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install pillow
          pip install pymupdf

      - name: Build the application
        run: |
          pyinstaller --onefile --windowed pata8ee.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: macOS-app
          path: dist/pata8ee
