name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.2'  # 必要なPythonのバージョンを指定

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pillow fitz tkinterdnd2 pymupdf

    - name: Install Xvfb
      run: sudo apt-get install -y xvfb

    - name: Run application with Xvfb
      run: |
        Xvfb :99 -screen 0 1024x768x16 &
        export DISPLAY=:99
        python your_script_name.py
