name: Build Windows Application_pata14e

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pillow tkinterdnd2 pymupdf

      - name: Download and install tkdnd library
        run: |
          curl -L -o tkdnd2.9.2.zip https://sourceforge.net/projects/tkdnd/files/tkdnd/2.9/tkdnd2.9.2.zip/download
          powershell -Command "Expand-Archive -Path tkdnd2.9.2.zip -DestinationPath tkdnd2.9.2"
          mkdir -p $env:APPDATA\Python\Python39\tcl\tkdnd
          cp tkdnd2.9.2/libtkdnd2.9.dll $env:APPDATA\Python\Python39\tcl\tkdnd

      - name: Build the application
        run: |
          pyinstaller --onefile --windowed pata14e.py --add-data "$env:APPDATA\Python\Python39\tcl\tkdnd;tkdnd"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Windows-app
          path: dist/pata14e.exe
