name: Build macOS Application_pata15b

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pillow tkinterdnd2 pymupdf

      - name: Download and install tkdnd library
        run: |
          curl -L -o tkdnd2.8.zip https://sourceforge.net/projects/tkdnd/files/tkdnd/2.8/tkdnd2.8.zip/download
          unzip tkdnd2.8.zip -d tkdnd2.8
          mkdir -p $HOME/Library/Python/3.9/lib/tkdnd
          cp tkdnd2.8/libtkdnd2.8.dylib $HOME/Library/Python/3.9/lib/tkdnd

      - name: Build the application
        run: |
          pyinstaller --onefile --windowed pata15b.py --collect-data tkinterdnd2

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: macOS-app
          path: dist/pata15b
